import { v4 as uuidv4 } from "uuid";

export interface GroundingMetadata {
    webSearchQueries?: string[];
    searchEntryPoints?: unknown[];
    retrievalQueries?: string[];
}

export interface GenerateContentResponseUsageMetadata {
    promptTokenCount?: number;
    candidatesTokenCount?: number;
    totalTokenCount?: number;
}

// Based on google.adk.events.event_actions
export interface EventActions {
    skipSummarization?: boolean;
}

/**
 * LLM response class that provides the first candidate response from the
 * model if available. Otherwise, returns error code and message.
 */
export interface LlmResponse {
    content?: Content;
    groundingMetadata?: GroundingMetadata;
    partial?: boolean;
    turnComplete?: boolean;
    errorCode?: string;
    errorMessage?: string;
    interrupted?: boolean;
    customMetadata?: Record<string, unknown>;
    usageMetadata?: GenerateContentResponseUsageMetadata;
}

/**
 * Represents an event in a conversation between agents and users.
 * It is used to store the content of the conversation, as well as the actions
 * taken by the agents like function calls, etc.
 */
export interface Event extends LlmResponse {
    invocationId: string;
    author: string;
    actions: EventActions;
    longRunningToolIds?: string[];
    branch?: string;
    id: string;
    timestamp: number;
}

export interface VideoMetadata {
    /**
     * The frame rate of the video sent to the model. If not specified, the
     * default value will be 1.0. The fps range is (0.0, 24.0].
     */
    fps?: number;
    /**
     * Optional. The end offset of the video.
     */
    endOffset?: string;
    /**
     * Optional. The start offset of the video.
     */
    startOffset?: string;
}

export interface Blob {
    /**
     * Optional. Display name of the blob. Used to provide a label or filename to distinguish blobs.
     */
    displayName?: string;
    /**
     * Required. Raw bytes, represented as a base64-encoded string.
     */
    data?: string;
    /**
     * Required. The IANA standard MIME type of the source data.
     */
    mimeType?: string;
}

export interface FileData {
    /**
     * Optional. Display name of the file data.
     */
    displayName?: string;
    /**
     * Required. URI.
     */
    fileUri?: string;
    /**
     * Required. The IANA standard MIME type of the source data.
     */
    mimeType?: string;
}

/**
 * Required. Outcome of the code execution.
 */
export const Outcome = {
    OUTCOME_UNSPECIFIED: 'OUTCOME_UNSPECIFIED',
    OUTCOME_OK: 'OUTCOME_OK',
    OUTCOME_FAILED: 'OUTCOME_FAILED',
    OUTCOME_DEADLINE_EXCEEDED: 'OUTCOME_DEADLINE_EXCEEDED',
} as const;
export type Outcome = (typeof Outcome)[keyof typeof Outcome];

/**
 * Result of executing the [ExecutableCode].
 * Always follows a `part` containing the [ExecutableCode].
 */
export interface CodeExecutionResult {
    /**
     * Required. Outcome of the code execution.
     */
    outcome?: Outcome;
    /**
     * Optional. Contains stdout when code execution is successful, stderr or other description otherwise.
     */
    output?: string;
}

/**
 * Required. Programming language of the `code`.
 */
export const Language = {
    LANGUAGE_UNSPECIFIED: 'LANGUAGE_UNSPECIFIED',
    PYTHON: 'PYTHON',
} as const;
export type Language = (typeof Language)[keyof typeof Language];

/**
 * Code generated by the model that is meant to be executed, and the result returned to the model.
 */
export interface ExecutableCode {
    /**
     * Required. The code to be executed.
     */
    code?: string;
    /**
     * Required. Programming language of the `code`.
     */
    language?: Language;
}

/**
 * A function call.
 */
export interface FunctionCall {
    /**
     * The unique id of the function call.
     */
    id?: string;
    /**
     * Optional. The function parameters and values in JSON object format.
     */
    args?: { [key: string]: unknown };
    /**
     * Required. The name of the function to call.
     */
    name?: string;
}

/**
 * Specifies how the response should be scheduled in the conversation.
 */
export const FunctionResponseScheduling = {
    SCHEDULING_UNSPECIFIED: 'SCHEDULING_UNSPECIFIED',
    SILENT: 'SILENT',
    WHEN_IDLE: 'WHEN_IDLE',
    INTERRUPT: 'INTERRUPT',
} as const;
export type FunctionResponseScheduling =
    (typeof FunctionResponseScheduling)[keyof typeof FunctionResponseScheduling];

/**
 * A function response.
 */
export interface FunctionResponse {
    /**
     * Signals that function call continues, and more responses will be returned.
     */
    willContinue?: boolean;
    /**
     * Specifies how the response should be scheduled in the conversation.
     */
    scheduling?: FunctionResponseScheduling;
    /**
     * Optional. The id of the function call this response is for.
     */
    id?: string;
    /**
     * Required. The name of the function to call.
     */
    name?: string;
    /**
     * Required. The function response in JSON object format.
     */
    response?: { [key: string]: unknown };
}

/**
 * A datatype containing media content.
 * Exactly one field within a Part should be set.
 */
export interface Part {
    /**
     * Metadata for a given video.
     */
    videoMetadata?: VideoMetadata;
    /**
     * Indicates if the part is thought from the model.
     */
    thought?: boolean;
    /**
     * Optional. Inlined bytes data.
     */
    inlineData?: Blob;
    /**
     * Optional. URI based data.
     */
    fileData?: FileData;
    /**
     * An opaque signature for the thought so it can be reused in subsequent requests.
     */
    thoughtSignature?: string; // bytes as base64 string
    /**
     * Optional. Result of executing the [ExecutableCode].
     */
    codeExecutionResult?: CodeExecutionResult;
    /**
     * Optional. Code generated by the model that is meant to be executed.
     */
    executableCode?: ExecutableCode;
    /**
     * Optional. A predicted [FunctionCall] returned from the model.
     */
    functionCall?: FunctionCall;
    /**
     * Optional. The result output of a [FunctionCall].
     */
    functionResponse?: FunctionResponse;
    /**
     * Optional. Text part (can be code).
     */
    text?: string;
}

/**
 * Contains the multi-part content of a message.
 */
export interface Content {
    /**
     * List of parts that constitute a single message.
     */
    parts?: Part[];
    /**
     * Optional. The producer of the content. Must be either 'user' or 'model'.
     */
    role?: 'user' | 'model' | 'context';
}

export const NewMessage = (message: string, role: 'user' | 'model' | 'context'): Event => {
    return {
        author: role,
        content: {
            role: role,
            parts: [
                { text: message }
            ]
        },
        invocationId: uuidv4(),
        actions: {
            skipSummarization: false
        },
        longRunningToolIds: [],
        branch: '',
        id: uuidv4(),
        timestamp: Date.now()
    }
}